Document: dbusgpio
Title: Debian dbusgpio Manual
Author: <insert document author here>
Abstract: This manual describes what dbusgpio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dbusgpio/dbusgpio.sgml.gz

Format: postscript
Files: /usr/share/doc/dbusgpio/dbusgpio.ps.gz

Format: text
Files: /usr/share/doc/dbusgpio/dbusgpio.text.gz

Format: HTML
Index: /usr/share/doc/dbusgpio/html/index.html
Files: /usr/share/doc/dbusgpio/html/*.html
